// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.

public enum LayerNames
{
    Default = 0,
    TransparentFX = 1,
    Ignore_Raycast = 2,
    Water = 4,
    UI = 5,
    Wall = 6,
    Entities = 7,
    Character = 8,
    Ground = 9,
    Reticle = 10,
    Projectiles = 11,
}
